sidoh/esp8266_milight_hub

- lib/MiLight/MiLightClient.cpp
- lib/MiLight/MiLightClient.h
- lib/MiLight/MiLightRadio.cpp
- lib/MiLight/MiLightRadio.h
- lib/MiLight/MiLightRadioConfig.h
- lib/MiLight/PL1167_nRF24.cpp
- lib/MiLight/PL1167_nRF24.h
- lib/WebServer/MiLightHttpServer.cpp
- lib/WebServer/MiLightHttpServer.h
- web/index.html
Sniff a single channel set instead of looping through them. Should make sniffing more robust, and makes it easier to handle the fact that the new protocol is of a different length.
> Sniff single channelset

- lib/MiLight/LT8900MiLightRadio.cpp
- lib/MiLight/LT8900MiLightRadio.h
- lib/MiLight/MiLightRadio.h
- lib/MiLight/NRF24MiLightRadio.cpp
This simplifies the code to handle reads from the LT8900 at the cost of not handling duplicates. The main advantage is that it's more responsive.
I could be wrong, but I don't think it's important to handle duplicate packets for this use case. Just about always the user is only going to want to know the ID of their remote.
@WoodsterDK, would you mind sanity-checking this when you get the chance?
> Refactor LT8900 reads

- lib/MiLight/CctPacketFormatter.cpp
- lib/MiLight/CctPacketFormatter.h
Add checksum of the 7 packet bytes (including packet length = 7).
Without it, several CCT bulbs cannot be linked and do not respond
on commands. The CctPacketFormatter.cpp protocol is now identical
to the FUT006 remote CCT controller.
The CCT protocol is as follows:
```
Byte 0: Packet length = 7 bytes
Byte 1: CCT protocol 0x5A
Byte 2 and 3: Device ID (16-bit)
Byte 4: Zone 0..4
Byte 5: Bulb command
Byte 6: Packet sequence number 0..255
Byte 7: Checksum over previous bytes 0..6
Byte 8: CRC LSB over bytes 0..7
Byte 9: CRC MSB over bytes 0..7
```
Tested with FUT011: 5W GU10 Dual White LED Spotlight, MiLight Hub web interface in CCT mode.
> Bufix checksum in CCT packet.

- lib/MiLight/RgbCctPacketFormatter.cpp
Change the default color tempreture for the rgb_cct protecol when pressing the "white mode" button from 0 (cold white) to 100 (warm white).
In a later update this schould become the last known color temperature stored in memory from the bulb state.
> Default color temp rgb_cct white mode 100

- .build_web.py
Fixes for building on Windows.  Sorry about the yanking of the PR's, but I had some issues with my repository that I needed to clean, and I took advantage of that to change to my main account (I forgot I was using a test account!)
> Fix build issues on Windows

- .build_web.py
- lib/MiLightState/GroupState.cpp
- lib/MiLightState/GroupState.h
Currently device type is compared for state, even though only device ID and group identify a bulb.  On some bulbs (the more modern ones, with RGBWW) support multiple controllers and switching between them is confusing when state is different across device types.  For me, this is a usability issue - it is easier for me to use when state remains the same when switching between remote types.  
The larger change here is some nice debugging code to help debug state changes.
> Improve state debugging

- README.md
- lib/LEDStatus/LEDStatus.cpp
- lib/LEDStatus/LEDStatus.h
- lib/Settings/Settings.cpp
- lib/Settings/Settings.h
- platformio.ini
- src/main.cpp
- web/src/js/script.js
This PR includes a new feature to update an LED with status of the device. See the README.md for details on the different flashing modes. It indicates if the Wifi is in AP mode, connected or failed, as well as signals when packets are traveling. The UI has been modified to support setting the pin of the LED, but it defaults to pin 2 (the built-in blue LED on NodeMCU) and supports inverted leds (which the NodeMCU is).
One important point here is that it is using a fork of WifiManager, because I needed a callback during the setup phase to flash the LEDs while waiting for setup. This fork is hosted on my GitHub, and it is referenced from the platform.io (so you need to reload those dependencies). I did a PR for the change to WifiManager, but it was rejected because they have a new feature …
> Add LED status to indicate wifi condition and packet handling

- lib/MiLight/CctPacketFormatter.cpp
- lib/MiLight/CctPacketFormatter.h
- lib/MiLight/FUT089PacketFormatter.cpp
- lib/MiLight/FUT089PacketFormatter.h
- lib/MiLight/MiLightClient.cpp
- lib/MiLight/MiLightClient.h
- lib/MiLight/MiLightRemoteConfig.cpp
- lib/MiLight/PacketFormatter.cpp
- lib/MiLight/PacketFormatter.h
- lib/MiLight/RgbCctPacketFormatter.cpp
- lib/MiLight/RgbCctPacketFormatter.h
- lib/MiLight/RgbPacketFormatter.cpp
- lib/MiLight/RgbPacketFormatter.h
- lib/MiLight/RgbwPacketFormatter.cpp
- lib/MiLight/RgbwPacketFormatter.h
- lib/MiLight/V2PacketFormatter.cpp
- lib/MiLight/V2PacketFormatter.h
- lib/MiLightState/GroupState.cpp
- lib/MiLightState/GroupState.h
- lib/MiLightState/GroupStateStore.cpp
- lib/MiLightState/GroupStateStore.h
- lib/Settings/Settings.cpp
- lib/Settings/Settings.h
- src/main.cpp
- web/src/js/script.js
Changes to saturation and temp changes on the v2 types (rgb+cct and fut089).  Detects if current bulb mode is unable to support the feature, and briefly switches modes, applies the change, and switches back.  This is especially important for temperature, otherwise it's hard to change temperature when using color mode. 
This may be a conceptual debate about the goals of MiLightHub... as this is changing the behavior of what the hub does vs. what a remote would do.  I think in the long run, it is a nice improvement as people use MQQT and the REST API to drive bulb changes, and this implements the functionality likely desired rather than pushing the limitations of the bulbs onto the user and their automation system.
> Handle inconsistency on saturation/temp on v2 types

- lib/MiLight/CctPacketFormatter.cpp
- lib/MiLight/PacketFormatter.cpp
- lib/MiLight/PacketFormatter.h
- lib/MiLightState/GroupState.cpp
- lib/MiLightState/GroupState.h
- web/src/js/script.js
This adds the ability to keep track enough information to determine when CCT bulbs are in a known state.  This has a few advantages:
* Can report brightness and color temperature state values for CCT
* Only need to send the minimum number of increment/decrement commands after the bulb is in a known state (e.g., decrease once to go from brightness 60 to 50).
> Keep track of increment command state

- lib/WebServer/MiLightHttpServer.cpp
Regarding #264 blank webpage on root (ERR_INCOMPLETE_CHUNKED_ENCODING)
The content length was still set manually by the sendHeader call.
Also applied fix by sending an empty string just before closing the client socket:
https://www.esp8266.com/viewtopic.php?p=66764#p66875
> Fix blank webpage on root (ERR_INCOMPLETE_CHUNKED_ENCODING)

- lib/MiLight/RgbPacketFormatter.cpp
- lib/MiLightState/GroupState.cpp
- lib/MiLightState/GroupState.h
- lib/MiLightState/GroupStateStore.cpp
- src/main.cpp
- test/d1_mini/test_state.cpp
Summary of changes:
* Add test for states
* Add method to patch one state with only the set fields from another
* Never persist group 0 state, except for devices that don't have groups (like RGB)
* Some miscellaneous fixes for RGB: decode brightness up/down, stateful brightness
> Apply patched updates to individual groups when updating group 0 (fixes #284)

- README.md
- lib/MiLight/MiLightClient.cpp
The overloaded method shouldn't ignore `deviceId` and `groupId`.
This small programming omission is only noticable if someone uses `MiLightClient` directly; `MiLightHttpServer` doesn't use this overload.
> Forward parameters in overloaded MiLightClient::prepare()

- lib/Udp/V6RgbCctCommandHandler.cpp
This fixes #319 for me and UDP messages now set the same colors as my iBox.
I assume the call in the preset method would need to be similarly adjusted but I have no way of testing that at this time and I would like some feedback before spending more time on this.
> Fix UDP v6 RgbCct color skew

- README.md
Because of the explicit link to this guide I kind of assumed the right pin was used by default which is not the case. The guide puts the CE pin on GPIO 4, not GPIO 16. Maybe it will save others some time if this was added to the readme.
> Improve NRF24L01+ pin configuration

- README.md
- lib/Settings/Settings.h
Turns out I didn't properly read your proposed changes in #367 as currently the description is "from 4 to 16" while it should be the other way around. The default is set to GPIO 16 and it needs to be changed to GPIO 4 to work when following the linked guide to install the antenna. As you stated there is no real reason GPIO 16 is picked by default I think it would save others some headaches (just like me) if it changed to GPIO 4. I've also removed the additional copy added to the README.md as this was wrong and correcting it would no longer be required.
> Change default CE pin from 16 to 4

- lib/MiLight/MiLightClient.cpp
- lib/MiLightState/GroupState.cpp
- lib/MiLightState/GroupState.h
- lib/MiLightState/GroupStateStore.cpp
- lib/MiLightState/GroupStateStore.h
- lib/WebServer/MiLightHttpServer.cpp
- lib/WebServer/MiLightHttpServer.h
- platformio.ini
- src/main.cpp
- test/remote/helpers/state_helpers.rb
- test/remote/lib/api_client.rb
- test/remote/spec/state_spec.rb
This change makes interplay between group 0 (the "all" group) and member groups more intuitive.
Previously, behavior was simple, but caused confusion when users expected group 0 to track its own state (e.g., #318).  Since 1.8, group 0 state was not tracked (#284).
This change makes the interplay more complex, but hopefully more intuitive.
* Group 0 will have its own state.  As was the case previously, applying a change to group 0 will fan out to individual groups.
* When an individual group changes a field, group 0 state for that field will be cleared.
```
$ curl -H 'content-type: application/json' -X PUT -d '{"status":"on","level":10,"kelvin":100}' milight-hub/gateways/0x2200/rgb_cct/0
$ curl milight-hub/gateways/0x2200/rgb_cct/0 …
```
> Improvements in group 0 behavior

- lib/MiLightState/GroupState.cpp
- lib/MiLightState/GroupState.h
- lib/MiLightState/GroupStateStore.cpp
- src/main.cpp
- test/remote/spec/state_spec.rb
A regression was introduced in the 1.9.0-dev12, breaking the increment/decrement state tracking added in a previous version.  This fixes the regression and adds a test.
> Fix scratch state regression

- lib/MQTT/MqttClient.cpp
- test/remote/lib/mqtt_client.rb
- test/remote/spec/mqtt_spec.rb
Both of these tokens are supported for state/update topic patterns.  Since the `:device_id` token for the command pattern supports both hexadecimal and decimal IDs, support for `:dec_device_id` and `:hex_device_id` was not added.
This can cause more confusion than it's worth (see #427).  This adds support.
> Add support for :dec_device_id and :hex_device_id in command topic

- lib/MiLight/CctPacketFormatter.cpp
- lib/MiLight/RgbwPacketFormatter.cpp
- lib/MiLightState/GroupState.cpp
- test/remote/helpers/state_helpers.rb
- test/remote/spec/state_spec.rb
* Fix packet parsing for RGBW and CCT handlers to properly recognize night_mode packets
* Fix state patching for night_mode
* Add night_mode tests for all bulb types (save for RGB, which doesn't support it)
> Fix night mode state handling for CCT and RGBW

- lib/Radio/MiLightRadioConfig.cpp
- lib/Radio/MiLightRadioConfig.h
- lib/Radio/NRF24MiLightRadio.cpp
- lib/Radio/PL1167_nRF24.cpp
- lib/Radio/PL1167_nRF24.h
- lib/Radio/RadioUtils.cpp
- lib/Radio/RadioUtils.h
Fixes #266 
Radio optimizations added in a much earlier version introduced a bug where RGB commands sent from remotes were not picked up by espMH (RGB commands sent from another espMH instance would be received, however).
This fixes that.  The fundamental issue is that the PL1167 includes a "preamble" and a "trailer" field in the transmitted packet, which appear to be generated as a function of the syncword.  These were hardcoded, but RGB uses a different preamble/trailer.
More detailed notes on the investigation can be found here:
https://github.com/sidoh/esp8266_milight_hub/issues/266#issuecomment-507109415
> Bugfix: RGB listens with milight remote

- platformio.ini
There was a compilation error when building the external Websockets dependency with latest Arduino libraries (2.5.X).
It was caused by SSL code changes in Arduino and since has been fixed in Websockets 2.2.0.
See Links2004/arduinoWebSockets#447 for details.
> Fix broken build with latest Arduino libs - bump Websockets to ~2.2.0

- lib/MQTT/MqttClient.cpp
- platformio.ini
With a smaller buffer it's possible that too long last will message will prevent MQTT client from connecting to the MQTT broker. More details in #613.
I also made logging a little verbose, as it was important for me to see MQTT connection rc code.
Closes #613
> Increased MQTT packet buffer

- lib/Transitions/ColorTransition.cpp
- lib/Transitions/ColorTransition.h
Fix for a memory leak which could occur when a light does a color transition to itself.
Example of a transition being stuck:
```
{
"transitions": [
{
"id": 1520,
"period": 4294967295,
"last_sent": 0,
"bulb": {
"device_id": 1,
"group_id": 1,
"device_type": "rgb_cct"
},
"type": "color",
"current_color": [
255,
167,
91
],
"end_color": [
255,
167,
91
],
"step_sizes": [
0,
0,
0
]
},
}
````
#600 #523
> Fix color transition memory leak

- lib/MQTT/HomeAssistantDiscoveryClient.cpp
Added "min_mireds" & "max_mireds" to the HA discovery payload so the system know the scale is not the standard 150-500 range and adjust the scale.
> Added "min_mireds" & "max_mireds" to the HA discovery payload

- lib/MQTT/HomeAssistantDiscoveryClient.cpp
Even after re-reading the docs, I think I was doing this correctly?
https://www.home-assistant.io/integrations/mqtt/
But was definitely getting the error mentioned in #804. Removing this fixes the issue and I don't think this guy was serving any function except that the docs encourage the origin information to be included.
So away it goes.
> Remove `origin` key from discovery payload, which is apparently wrong?

- lib/MiLight/FUT089PacketFormatter.cpp
- lib/MiLight/FUT089PacketFormatter.h
It uses the same protocol as FUT089, but has separate commands for color temperature and saturation.
Closes #844
Please review my naming changes (I used FUT092 in the same enum as FUT089 options, not sure if that is appropriate).
I chose not to change the `updateTemperature` and `updateSaturation` methods, because that would require testing on a RGB light. However, it should be possible to use the new commands to avoid the current mode-dependent behavior.
> Add support to decode the FUT092 remote

- README.md
As noted in #860 , I can testify that the B05 remote is supported.
> Adds B05 Milight remote as supported Device #860
