sidoh/esp8266_milight_hub

lib/MiLight/MiLightClient.cpp, lib/MiLight/MiLightClient.h, lib/MiLight/MiLightUdpServer.cpp, lib/MiLight/MiLightUdpServer.h, lib/Settings/Settings.cpp, lib/Settings/Settings.h, lib/WebServer/WebServer.cpp, src/main.cpp, web/index.html
This allows allows users to specify gateway UDP servers which respond to the existing Milight UDP protocol on different ports.
=> Add support for Milight UDP protocol

lib/MiLight/MiLightButtons.h, lib/MiLight/MiLightClient.cpp, lib/MiLight/MiLightClient.h, lib/MiLight/MiLightRadio.cpp, lib/MiLight/MiLightRadio.h, lib/MiLight/MiLightRadioConfig.h, lib/MiLight/MiLightUdpServer.cpp, lib/MiLight/MiLightUdpServer.h, lib/MiLight/PL1167_nRF24.cpp, lib/MiLight/PL1167_nRF24.h, platformio.ini, src/main.cpp, web/index.html
=> Add support for CCT (Adjustable white) bulbs

lib/WebServer/MiLightHttpServer.cpp
=> apply settings on server boot

data/web/index.html, lib/MiLight/MiLightClient.cpp, lib/MiLight/MiLightClient.h, lib/MiLight/MiLightRadio.h, lib/MiLight/MiLightRadioInterface.h, lib/MiLight/MiLightRadioPL1167_LT8900.h, lib/MiLight/MiLightRadioPL1197_LT8900.cpp, lib/MiLight/RadioStack.h, lib/Settings/Settings.cpp, lib/Settings/Settings.h, platformio.ini, src/main.cpp
Added new RF interface, but still some minor issues:
- web app does not store interface type
- web app crashes on submit, might very well be the addition of the radio interface type
- the actual transmit on the PL1167 interface sometimes does not come through,
will look at it
=> v1.2.0 - adding support of different RF modules

lib/MiLight/LT8900MiLightRadio.cpp, lib/MiLight/LT8900MiLightRadio.h, lib/MiLight/MiLightClient.h, lib/MiLight/MiLightRadioFactory.cpp
Speed optimisation and bug fixes:
- Changes to dual module has been verified to work.
=> Speed optimisation and bug fixes

README.md, lib/WebServer/MiLightHttpServer.cpp, lib/WebServer/MiLightHttpServer.h, src/main.cpp
=> Implement mDNS and SSDP

lib/Udp/V5MiLightUdpServer.cpp
=> Fix bugs in v5 UDP command handler

lib/MiLight/MiLightClient.cpp, lib/MiLight/MiLightClient.h
I have added code to switch to white mode if the payload contains white_value
This is for Issue #100
=> Switch to white if white_value in payload

README.md, lib/WebServer/MiLightHttpServer.cpp, src/main.cpp
As promised, this pull request solves #120 and also #123.
I also changed `README.md` and added the wifi password. However, you possibly might want to put this information at a more prominent place.
Hope that helps :)
=> Solving issues #120 and #123

.gitignore, lib/Settings/Settings.h, platformio.ini
This turned out to be exceptionally easy.  Thanks for all your work here!
=> Modified to work with Adafruit Feather Huzzah

README.md
The current link is to a slightly less helpful website.
=> Change URL to NRF24 connection guide

web/src/index.html
New Night button on the web page.  This should be the same as the last PR, just moved my git account around.
=> Added 'Night' button

lib/MiLightState/GroupState.cpp
@cmidgley let me know if you think we should keep these and I can revert.
=> remove commented out code

README.md, platformio.ini
=> Remove stale instructions for PlatformIO; don't use staging version of Arduino SDK

lib/MQTT/BulbStateUpdater.cpp, lib/MiLight/CctPacketFormatter.cpp, lib/MiLight/FUT089PacketFormatter.cpp, lib/MiLight/RgbCctPacketFormatter.cpp, lib/MiLight/RgbPacketFormatter.cpp, lib/MiLight/RgbwPacketFormatter.cpp, lib/MiLight/V2PacketFormatter.cpp, lib/MiLight/V2PacketFormatter.h, lib/MiLightState/GroupStateStore.cpp, lib/MiLightState/GroupStateStore.h, lib/WebServer/MiLightHttpServer.cpp, lib/WebServer/MiLightHttpServer.h, src/main.cpp
This should hopefully fix #327 and maybe some related issues.
=> attempt fix for #327

lib/MQTT/BulbStateUpdater.cpp, lib/MiLight/CctPacketFormatter.cpp, lib/MiLight/FUT089PacketFormatter.cpp, lib/MiLight/RgbCctPacketFormatter.cpp, lib/MiLight/RgbPacketFormatter.cpp, lib/MiLight/RgbwPacketFormatter.cpp, lib/MiLight/V2PacketFormatter.cpp, lib/MiLight/V2PacketFormatter.h, lib/MiLightState/GroupStateStore.cpp, lib/MiLightState/GroupStateStore.h, lib/Udp/V6RgbCctCommandHandler.cpp, lib/WebServer/MiLightHttpServer.cpp, lib/WebServer/MiLightHttpServer.h, platformio.ini, src/main.cpp
* ( #319 ) Correct offset for RGB+CCT in V6 UDP (thanks, @amelchio!)
* Fix broken build for newest pio platform.  See #334.
* ( #327, #328 (?) ) Fix bug where sniffing group 0 packet caused crashes or inconsistent behavior.
=> v1.8.2 release

README.md, lib/WebServer/MiLightHttpServer.cpp
=> Fix radio config endpoint

README.md, lib/MiLightState/GroupState.cpp, lib/MiLightState/GroupState.h, lib/MiLightState/GroupStateStore.cpp, src/main.cpp, test/d1_mini/test.cpp
* ( #318 ) Group 0 updates did not affect constituent group states.  This has been fixed
=> Fix group0 state

README.md
=> Improve pinout documentation in README.md

README.md
Thanks @saerdnaer for the improvements!
=> Improve pinout docs

lib/MiLightState/GroupState.cpp, test/remote/spec/state_spec.rb
=> Fix night mode behavior under 1.9.0, add test

lib/MiLightState/GroupState.cpp, lib/MiLightState/GroupStateStore.cpp, platformio.ini, test/d1_mini/test.cpp, test/remote/spec/state_spec.rb
This bug seems to be a technicality in internal state tracking, but was causing embedded tests to fail.
=> Fix bug in patch state, improve embedded tests

lib/Settings/Settings.h, test/remote/spec/settings_spec.rb
=> Fix group state field default

lib/MiLight/MiLightClient.cpp, test/remote/spec/state_spec.rb
=> Bugfix: boolean values for state/status field are not properly recognized

lib/MiLight/MiLightClient.cpp, test/remote/settings.json.example, test/remote/spec/state_spec.rb
Fixes #496.  This was a regression in the v1.10 branch.
=> Bugfix: handle effect key

.gitignore, platformio.ini
changed lib depends,
git ignore dist files
=> Fix pio errors

lib/MQTT/HomeAssistantDiscoveryClient.cpp
Generate uniq_id from ESP ChipID and alias
Closing #607
=> Add uniq_id to MQTT Discovery message

lib/MiLight/MiLightClient.cpp
Non breaking fix for https://github.com/sidoh/esp8266_milight_hub/pull/666
=> Act on brightness_up and brightness_down

lib/DataStructures/LinkedList.h
Resolving bugs mentioned in issue #775
=> Fixed bugs in LinkedList

.github/workflows/build.yaml, .github/workflows/release.yaml, .prepare_docs, .prepare_release, lib/MQTT/HomeAssistantDiscoveryClient.cpp
I noticed a few cosmetic things were broken with HomeAssistant discovery. The produced Device didn't have a name, and manufacturer/model weren't filled out appropriately. This fixes those things.
=> Fix HomeAssistant discovery
